modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/yuuki1293/ChiselSeparateByChunk/issues"
license = "MIT"
clientSideOnly=true

[[mods]]
modId = "chiselsbc"
version = "${version}"
displayName = "Chisel: Separated by Chunks"
authors = "yuuki1293"
description = '''
This mod makes Chisel’s connected texture blocks disconnect at chunk borders to make the chunk boundaries more visually distinguishable.
'''
logoFile = "logo.png"

[[dependencies.chiselsbc]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselsbc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselsbc]]
modId = "athena"
mandatory = true
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "CLIENT"
