modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "chiselsbc"
version = "${version}"
displayName = "Chisel: Separated by Chunks"
authors = "yuuki1293"
description = '''
This mod makes Chisel’s connected texture blocks disconnect at chunk borders to make the chunk boundaries more visually distinguishable.
'''
#logoFile = ""

[[dependencies.chiselsbc]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselsbc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiselsbc]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
